version: 0.0
os: linux
files:
  - source: build.zip
    destination: /deploy
hooks:
  AfterInstall:
    - location: scripts/createBuild.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/startBot.sh
      timeout: 300
      runas: root