# This is a basic workflow to help you get started with Actions
# A change in a new branch
#Another fix
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build TypeScript Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # runs yarn install command
      
      - name: Build project
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      
      - name: Zip build
        run: zip -r build.zip build

  continuous-deployment:
    name: Configure AWS Deployment
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Create CodeDeploy Development
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name Git_Application \
            --deployment-group-name Deployment_Group \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}

  


    
